language: java
jdk: 
- oraclejdk7
 
-script: mvn clean verify

# deploy if the first job is successful; should be replaced by an after_all_success if travis finally supports it
after_success: 
- if [[ $TRAVIS_JOB_NUMBER == *1 ]]; then mvn -DskipTests deploy --settings deploysettings.xml; fi

env: 
  global: 
   - secure: "QdyDWuy4PtW5VhCaMj1V+msvkHK/Z8RkzaNgCYSWFuXodxuXFzAMjYNIj+x1nyJLnon3PJLZbrHzxJSllHnygsYMViEd+axF0cNzOTvZY4ZuCEdGgsYwSUkwDvHnkK2CjtioTGmYQvdMbYHaJ8PX2KHPgUy6KYrVj3DQ5dlvgAU="
   - secure: "WCSDotat1WvPK91bs3KzLgYKGMPUwlUN+Gat3X270DD1ZI2x9oCEJbZjtaalrJGTeVGOIHMhHFQ+JCljIBLUkUWFQTpms5B0dKtUI0/NpJBAhXcK5Hfsfo5dwLVR8sKbtOkDc40YCE2BoY6syIVK3PWG6tmDgqhvwAr2gmTilMo="
